name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v10
      with:
        configuration: ./phpunit.xml
    - uses: php-actions/phpstan@v3
      with:
        configuration: ./phpstan.neon